version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign

formatters:
  enable:
    - gofmt

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
