# GoReleaser configuration for pane-patrol
# https://goreleaser.com

version: 2

project_name: pane-patrol

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: pane-patrol
    ldflags:
      - -s -w -X github.com/timvw/pane-patrol/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

# Linux packages via nfpm
nfpms:
  - package_name: pane-patrol
    vendor: timvw
    homepage: https://github.com/timvw/pane-patrol
    maintainer: Tim Van Wassenhove <tim@vanwassenhove.be>
    description: ZFC-compliant terminal pane monitor for AI coding agents
    license: MIT
    formats:
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin
    contents:
      - src: ./LICENSE
        dst: /usr/share/licenses/pane-patrol/LICENSE

# Homebrew tap
brews:
  - repository:
      owner: timvw
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/timvw/pane-patrol
    description: ZFC-compliant terminal pane monitor for AI coding agents
    license: MIT
    install: |
      bin.install "pane-patrol"
    test: |
      assert_match "pane-patrol version", shell_output("#{bin}/pane-patrol version")

# AUR package
aurs:
  - name: pane-patrol-bin
    homepage: https://github.com/timvw/pane-patrol
    description: ZFC-compliant terminal pane monitor for AI coding agents
    maintainers:
      - 'Tim Van Wassenhove <tim@vanwassenhove.be>'
    license: MIT
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/pane-patrol-bin.git'
    package: |-
      install -Dm755 pane-patrol "${pkgdir}/usr/bin/pane-patrol"
      install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/pane-patrol/LICENSE"

release:
  github:
    owner: timvw
    name: pane-patrol
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
